### ISSUE TITLE
Proxy-mode support

### ISSUE THREAD

**Issue by rkoster** [adaptivdesign/odooku-compat#1]
While I was trying to setup google oAuth, I found that odoo was no picking up the request protocol in the redirect (when trying to login from https it would have a redirect_url with http).

I found the following related odoo issue https://github.com/odoo/odoo/pull/10363, in this issue they [also mention](https://github.com/odoo/odoo/pull/10363#issuecomment-223286990) `--proxy-mode`.

I have tried adding `--proxy-mode` but got:

```
2016-10-12T09:56:54.003117+00:00 app[web.1]: Error: no such option: --proxy-mode
```

**Comment by adaptivdesign** [comment]
Alright clearly that one is missing. Will add support for that one. I am currently fixing the vagrant development machine.

**Comment by adaptivdesign** [comment]
Added this in the 10.0 branch
