### ISSUE TITLE
you mail is not working

### ISSUE THREAD

**Issue by aziznesm** [adaptivdesign/odooku-compat#3]
Please contact me on 
aaziz@makhotels.com

for project setup

**Comment by adaptivdesign** [comment]
Send you an email, hope you've got it :)

**Comment by aziznesm** [comment]
i got your mail

but i can't send you mail :S

**Comment by aziznesm** [comment]
add me on skype: aziznesm

**Comment by adaptivdesign** [comment]
Ok will do, I'll add you tomorrow! Not at home right now.

**Comment by aziznesm** [comment]
Still waiting for you.
