### ISSUE TITLE
Newrelic vs long polling

### ISSUE THREAD

**Issue by rkoster** [adaptivdesign/odooku-compat#4]
I'm currently using newrelic and found the reports to be less then usefull since they are polluted with all the long polling requests (which can take up to 30s by design).

An option would be to ignore those requests but for this the newrelic agent needs to be configured by using the [ignore_transaction](https://docs.newrelic.com/docs/agents/python-agent/customization-extension/python-transaction-api#ignore_transaction) api.

Before working on this I wanted to know if this is a known problem and if there are maybe other solutions.

**Comment by adaptivdesign** [comment]
Hey Ruben,

Long polling requests are indeed a problem. Further more request timeouts that can occur on the Heroku platform (when installing an app for example). Thats why I've added Websocket support in Odooku. 

You can enable websocket support by running with the '--ws' flag, and making sure the websocket addon module is installed. If no websocket can be created, Odooku falls back to the regular connection.

I haven't looked that much recently into newrelic integration. Looking at the ignore transaction API, it shouldn't be much of a problem to integrate that too.

**Comment by rkoster** [comment]
websocket support looks nice!, however we are using odoo 9.0. Would this be something which could be backported to the 9.0 branch, or are there technical reasons for no 9.0 support?

**Comment by adaptivdesign** [comment]
No there are no technical reasons. Currently I'm only focusing my efforts on 10.0. If I had any reasonable amount of time left, I would look into it. 

Your best bet right now would be to fork Odooku Compat and modify the 9.0 version to work with the ignore_transaction api.
